# environment settings
seed: 0
precision: bf16
strategy: deepspeed
gradient_clip_val: 2.
slurm: False
num_nodes: 1

# data arguments
dataset: unified
taskonomy: True
coco: True
midair: True
mpii: True
deepfashion: True
freihand: True
midair_stereo: True
coco_stereo: True
task_sampling_weight: [1., 3., 3.]
task: unified
base_task: True
cont_task: True
cat_task: True
task_group: None
coco_cropped: True
use_stereo_datasets: False
no_coco_kp: False

num_workers: 8
global_batch_size: 8
shot: 4
support_idx: 0
eval_shot: 16
max_channels: 4
domains_per_batch: 2
eval_batch_size: 8
eval_size: 80
img_size: 224
base_size: -1
vis_size: -1
image_augmentation: True
label_augmentation: True
autocrop: False
chunk_size: 1
channel_chunk_size: 17
channel_sampling: -1

# model arguments
image_encoder: beitv2_large_patch16_224
label_encoder: vit_large_patch16_224
n_attn_heads: 16
decoder_features: 256
image_encoder_drop_path_rate: 0.1
label_encoder_drop_path_rate: 0.
n_input_images: 1
separate_alpha: False
matching_alpha_init: 0.
matching_alpha_temp: 0.05

# training arguments
n_steps: 400000
n_schedule_steps: -1
optimizer: adam
lr: 0.0001
lr_pretrained: 0.00001
lr_schedule: poly
lr_warmup: 5000
lr_warmup_scale: 0.
schedule_from: 0
weight_decay: 0.
lr_decay_degree: 0.9
mask_value: -1.
early_stopping_patience: -1
loss_type: hybrid
con_coef: 1.0
bce_coef: 1.0
ssl_coef: 1.0
from_scratch: False
scale_ssl: True

# logging arguments
log_dir: TRAIN
save_dir: TRAIN
load_dir: TRAIN
val_iter: 10000
monitor: summary/mtrain_valid_pred
load_step: -1
