# environment settings
seed: 0
precision: bf16
strategy: ddp
num_nodes: 1

# data arguments
dataset: fsc147
task: object_counting
class_wise: False
class_name: none
shot: 50
img_size: 512
base_size: 592
vis_size: 592
support_idx: 0
coord_path: none
autocrop: False
autocrop_minoverlap: 0.
autocrop_rescale: 3

# dataloader arguments
num_workers: 1
eval_shot: 50
eval_batch_size: 1
eval_size: -1
support_idx: 0
chunk_size: 1
channel_chunk_size: 1

# logging arguments
log_dir: TEST_FSC147
save_dir: FINETUNE_FSC147
load_dir: TRAIN
load_step: 400000
load_path: none
result_dir: none