# environment settings
seed: 0
precision: bf16
strategy: ddp
num_nodes: 1

# data arguments
dataset: cellpose
task: cellpose
class_wise: False
class_name: none
shot: 50
img_size: 224
base_size: 256
vis_size: 256
support_idx: 0
randomflip: True
randomjitter: False
randomrotate: False
randomblur: False
coord_path: none
autocrop: True
autocrop_minoverlap: 0.5
autocrop_rescale: 1

# dataloader arguments
num_workers: 1
global_batch_size: 8
eval_shot: 50
eval_batch_size: 10
eval_size: -1
chunk_size: -1
channel_chunk_size: 1
channel_sampling: -1

# model arguments
attn_dropout: 0.5
n_input_images: 2
separate_alpha: False
monitor: AP50_inverted

# training arguments
n_steps: 8000
n_schedule_steps: -1
optimizer: adam
loss_type: cellpose
mask_value: -1.
early_stopping_patience: -1

# learning rate arguments
lr: 0.003
lr_pretrained: 0.0002
lr_schedule: constant 
lr_warmup: 0
lr_warmup_scale: 0.
schedule_from: 0
weight_decay: 0.
lr_decay_degree: 0.9

# parameter arguments
from_scratch: False
head_tuning: False
input_embed_tuning: False
output_embed_tuning: False
relpos_tuning: True
label_decoder_tuning: True

# logging arguments
log_dir: FINETUNE_CELLPOSE
save_dir: FINETUNE_CELLPOSE
load_dir: TRAIN
val_iter: 1000
load_step: 400000